SAGEMAKER:
  ARN: '<FILL YOUR ARN HERE>'
  INSTANCE_TYPE: 'local_gpu'
  INSTANCE_COUNT: 1
  SPOT_INSTANCE: False
  JOB_NAME: 'gan_training'

ECR:
  IMAGE: 'gan_training'
  TAG: 'build_0_1'

S3:
  TRAINING_DATA: 's3://training_data/data'
  EXPERIMENT_NAME: 'ml_engineer_1/gan_training/training_20210816_v01'

TRAINING:
  CFG: 'configs/training_config.yaml'
