SAGEMAKER:
  ARN: '**INSERT SageMaker Trianing Execution Role ARN HERE**'
  INSTANCE_TYPE: 'local_gpu'
  SPOT_INSTANCE: False
  JOB_NAME: 'gan_training'

ECR:
  IMAGE_NAME: 'gan_training'
  TAG: 'build_0_1'

S3:
  TRAINING_DATA: 's3://sagemaker-gan-training-data/data'
  SAGEMAKER_RESULTS_BUCKET: 'sagemaker-gan-results'
  EXPERIMENT_NAME: 'ml_engineer_1/gan_training/training_20210816_v01'

TRAINING:
  CONFIG_FILE: 'configs/training_config.yaml'
