DATALOADER:
  NUM_WORKERS: 12
  BATCH_SIZE: 128
  IMAGE_SIZE: 64

GENERATOR:
  NUM_CHANNELS: 3
  LATENT_SIZE: 100
  FEATURE_SIZE: 64

DISCRIMINATOR:
  NUM_CHANNELS: 3
  FEATURE_SIZE: 64

TRAINING:
  NUM_EPOCHS: 5
  LEARNING_RATE: 0.0002
  BETA_1: 0.5
  NUM_GPU: 1
